# Generated by Django 2.0.5 on 2018-05-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quemsomos',
            options={'verbose_name': 'Quem somos'},
        ),
    ]
